apiVersion: v1
kind: Namespace
metadata:
  name: qa
---
apiVersion: v1
kind: LimitRange
metadata:
  name: qa-limits
  namespace: qa
spec:
  limits:
  - type: Container
    defaultRequest: { cpu: "100m", memory: "128Mi" }
    default:        { cpu: "500m", memory: "512Mi" }
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: qa-quota
  namespace: qa
spec:
  hard:
    requests.cpu: "2"
    requests.memory: "4Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "20"
